//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<commissionorders> commissionorders { get; set; }
        public DbSet<documents> documents { get; set; }
        public DbSet<expertise_type> expertise_type { get; set; }
        public DbSet<experts> experts { get; set; }
        public DbSet<legalissues> legalissues { get; set; }
        public DbSet<qualifications> qualifications { get; set; }
    }
}
